name = "Spaghetti (Again)"
author = "Tropheus Jay"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a8fcae30a275f27c775ee202066274babbc5afcacde50ae0a1e00360fe67eb4"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.13"
