name = "Spaghetti (Again)"
author = "Tropheus Jay"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6130926edcd5c4cb40ed7525b67fa53d4376f2cd6e1c1e61387ff5c08ac7ddb"

[versions]
minecraft = "1.19.2"
quilt = "0.19.0-beta.5"
